// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mailservice.proto

/*
Package mailservice is a generated protocol buffer package.

It is generated from these files:
	mailservice.proto

It has these top-level messages:
	EmailRequest
	EmailResponse
*/
package mailservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EmailRequest - email request definition
type EmailRequest struct {
	Sender   string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Receiver string `protobuf:"bytes,2,opt,name=receiver" json:"receiver,omitempty"`
	Title    string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
}

func (m *EmailRequest) Reset()                    { *m = EmailRequest{} }
func (m *EmailRequest) String() string            { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()               {}
func (*EmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EmailRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *EmailRequest) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *EmailRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// EmailResponse - email response definition
type EmailResponse struct {
	Status bool `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *EmailResponse) Reset()                    { *m = EmailResponse{} }
func (m *EmailResponse) String() string            { return proto.CompactTextString(m) }
func (*EmailResponse) ProtoMessage()               {}
func (*EmailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EmailResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*EmailRequest)(nil), "mailservice.EmailRequest")
	proto.RegisterType((*EmailResponse)(nil), "mailservice.EmailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MailService service

type MailServiceClient interface {
	// put an email request an email
	PutEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
}

type mailServiceClient struct {
	cc *grpc.ClientConn
}

func NewMailServiceClient(cc *grpc.ClientConn) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) PutEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := grpc.Invoke(ctx, "/mailservice.MailService/PutEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MailService service

type MailServiceServer interface {
	// put an email request an email
	PutEmail(context.Context, *EmailRequest) (*EmailResponse, error)
}

func RegisterMailServiceServer(s *grpc.Server, srv MailServiceServer) {
	s.RegisterService(&_MailService_serviceDesc, srv)
}

func _MailService_PutEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).PutEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mailservice.MailService/PutEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).PutEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mailservice.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutEmail",
			Handler:    _MailService_PutEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mailservice.proto",
}

func init() { proto.RegisterFile("mailservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xb1, 0x0e, 0x82, 0x50,
	0x0c, 0x45, 0x45, 0x23, 0xc1, 0xa2, 0x83, 0x8d, 0x31, 0xc8, 0x64, 0x58, 0x74, 0x62, 0xd0, 0x4f,
	0x30, 0x8e, 0x26, 0xe6, 0xb9, 0xb8, 0x22, 0x76, 0x78, 0x09, 0x02, 0xbe, 0x16, 0xbe, 0xdf, 0x58,
	0x88, 0x61, 0x70, 0x3c, 0xbd, 0xe9, 0xed, 0x29, 0x2c, 0x5f, 0x99, 0x2d, 0x98, 0x5c, 0x6b, 0x73,
	0x4a, 0x6b, 0x57, 0x49, 0x85, 0xe1, 0x60, 0x94, 0xdc, 0x61, 0x7e, 0xfe, 0xb2, 0xa1, 0x77, 0x43,
	0x2c, 0xb8, 0x06, 0x9f, 0xa9, 0x7c, 0x92, 0x8b, 0xbc, 0xad, 0xb7, 0x9f, 0x99, 0x9e, 0x30, 0x86,
	0xc0, 0x51, 0x4e, 0xb6, 0x25, 0x17, 0x8d, 0x35, 0xf9, 0x31, 0xae, 0x60, 0x2a, 0x56, 0x0a, 0x8a,
	0x26, 0x1a, 0x74, 0x90, 0xec, 0x60, 0xd1, 0x37, 0x73, 0x5d, 0x95, 0x4c, 0x5a, 0x2d, 0x99, 0x34,
	0xac, 0xd5, 0x81, 0xe9, 0xe9, 0x60, 0x20, 0xbc, 0x64, 0xb6, 0xb8, 0x75, 0x46, 0x78, 0x82, 0xe0,
	0xda, 0x88, 0xae, 0xe2, 0x26, 0x1d, 0xea, 0x0f, 0x45, 0xe3, 0xf8, 0x5f, 0xd4, 0x5d, 0x4a, 0x46,
	0x0f, 0x5f, 0x5f, 0x3d, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x80, 0x7d, 0x64, 0xff, 0x00,
	0x00, 0x00,
}
